# Generated by Django 5.2.7 on 2026-01-05 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WorkdayAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, unique=True, verbose_name='補班日期')),
                ('compensate_for', models.DateField(verbose_name='補哪一天的假')),
                ('description', models.TextField(blank=True, verbose_name='說明')),
            ],
            options={
                'verbose_name': '補班日',
                'verbose_name_plural': '補班日',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='CalendarDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, unique=True, verbose_name='日期')),
                ('year', models.IntegerField(db_index=True, verbose_name='年份')),
                ('month', models.IntegerField(db_index=True, verbose_name='月份')),
                ('day', models.IntegerField(verbose_name='日')),
                ('weekday', models.IntegerField(help_text='0=週一, 1=週二, 2=週三, 3=週四, 4=週五, 5=週六, 6=週日', verbose_name='星期')),
                ('is_weekend', models.BooleanField(default=False, verbose_name='是否為週末')),
                ('is_holiday', models.BooleanField(db_index=True, default=False, verbose_name='是否為假日')),
                ('is_workday', models.BooleanField(db_index=True, default=False, verbose_name='是否為補班日')),
                ('holiday_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='假日名稱')),
                ('description', models.TextField(blank=True, null=True, verbose_name='說明')),
            ],
            options={
                'verbose_name': '日曆日期',
                'verbose_name_plural': '日曆日期',
                'ordering': ['date'],
                'indexes': [models.Index(fields=['year', 'month'], name='calendar_ap_year_b82754_idx'), models.Index(fields=['date'], name='calendar_ap_date_3f8a56_idx')],
            },
        ),
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='假日名稱')),
                ('date', models.DateField(db_index=True, verbose_name='日期')),
                ('year', models.IntegerField(db_index=True, verbose_name='年份')),
                ('holiday_type', models.CharField(choices=[('national', '國定假日'), ('flexible', '彈性放假'), ('adjusted', '調整放假')], default='national', max_length=20, verbose_name='假日類型')),
                ('is_lunar', models.BooleanField(default=False, verbose_name='是否為農曆假日')),
                ('description', models.TextField(blank=True, verbose_name='說明')),
            ],
            options={
                'verbose_name': '假日',
                'verbose_name_plural': '假日',
                'ordering': ['date'],
                'indexes': [models.Index(fields=['year', 'date'], name='calendar_ap_year_8462c3_idx'), models.Index(fields=['holiday_type'], name='calendar_ap_holiday_5178e9_idx')],
            },
        ),
    ]
